### PR TITLE
Nexus 2.8 rundeck

### PR DESCRIPTION
**Pull request by dkostovski**
I've tested the plugin with nexus-oss 2.6.0 and 2.8.1-01

### CODE REVIEW

**Comment by gschueler** [comment]
travis build failed due to "Detected Maven Version: 3.2.3 is not in the allowed range [3.0.4,3.1)"... not sure how to tell travis to use a different maven version.  Is that maven allowed range coming from the parent pom?

**Comment by dkostovski** [comment]
The enforcer rule is defined in nexus-oss parent [pom](https://github.com/sonatype/nexus-oss/blob/nexus-2.8.1-01/pom.xml#L588).
You can pass `-Denforcer.skip=true` to maven to ignore the enforcer rules, but then the build will fail.
The only way to have a successful build is to use maven version in the required range.

According to the [docs](http://docs.travis-ci.com/user/languages/java/) Travis has only one maven version.

**Comment by dkostovski** [comment]
Hi @gschueler 
Can you provide an update about the status of the pull request, whether or not it will be merged?

**Comment by gschueler** [comment]
hi @dkostovski trying a local build to verify and i will merge

**Pull request merged**
